---
title: "Met Table"
format: pdf
editor: visual
---

```{r, echo=FALSE}

library(gt)

event_avgs_maxmin <- readRDS('data/event_avgs_maxmin.rds')

# pretty table of event met stats ----
pretty_table <- event_avgs_maxmin |>
  # select(w_tree_event, variable, min, mean, max, total_snowfall) |>
  gt() |>
  tab_spanner(
    label = "Air Temperature (°C)",
    columns = ends_with("_t"),
  ) |>
  tab_spanner(
    label = "Wind Speed (m/s)",
    columns = ends_with("_u")
  ) |>
  tab_spanner(
    label = "Interception Efficiency (-)",
    columns = ends_with("_IP_troughs")
  ) |>
  cols_label(
    w_tree_event = "Start Date",
    duration = 'Duration (Hrs)',
    min_t = "Min",
    mean_t = "Mean",
    max_t = "Max",
    min_u = "Min",
    mean_u = "Mean",
    max_u = "Max",
    min_IP_troughs = "Min",
    mean_IP_troughs = "Mean",
    max_IP_troughs = "Max",
    total_snowfall = "Total Snowfall (mm)"
  ) |>
  cols_align(align = "center")  |>
  cols_width(
    w_tree_event ~ px(95),           # Set width for 'Start Date' column
    duration ~ px(70),               # Set width for 'Duration (Hrs)' column
    ends_with("_t") ~ px(50),         # Set equal width for Air Temperature columns
    ends_with("_u") ~ px(50),         # Set equal width for Wind Speed columns
    ends_with("_IP_troughs") ~ px(50),# Set equal width for Interception Efficiency columns
    total_snowfall ~ px(80)          # Set width for 'Total Snowfall' column
  ) |>
  fmt_number(
    columns = c(starts_with("min_"), starts_with("mean_"), starts_with("max_"), total_snowfall),
    decimals = 1
  )
```

\pagebreak

```{r, echo=FALSE}
#| label: tbl-sf-event-met
#| tbl-cap: "Meteorological statistics for the 26 snowfall events."

pretty_table
```

